import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

class PdfGeneratorService {
  // Font removed - uses default Helvetica

  Future<Uint8List> generateNarrativeReportPdf(Map<String, dynamic> report) async {
    final pdf = pw.Document();
    final dateFmt = DateFormat('dd MMMM yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => [
          _header('NARRATIVE REPORT'),
          pw.SizedBox(height: 16),
          _section('Activity Information', [
            _field('Activity Name', report['activityName'] ?? ''),
            _field('Type', report['activityType'] ?? ''),
            _field('Date', '${report['startDateMs'] != null ? dateFmt.format(DateTime.fromMillisecondsSinceEpoch(report['startDateMs'])) : ''} — ${report['endDateMs'] != null ? dateFmt.format(DateTime.fromMillisecondsSinceEpoch(report['endDateMs'])) : ''}'),
            _field('Location', report['location'] ?? ''),
            _field('Organiser', report['organiser'] ?? ''),
          ]),
          pw.SizedBox(height: 16),
          _section('People Reached', [
            _field('Total Participants', '${report['totalParticipants'] ?? 0}'),
            _field('Men / Women', '${report['men'] ?? 0} / ${report['women'] ?? 0}'),
            _field('Age: Under 18 / 18-35 / 36-59 / 60+', '${report['under18'] ?? 0} / ${report['age18to35'] ?? 0} / ${report['age36to59'] ?? 0} / ${report['age60plus'] ?? 0}'),
            _field('First-time Participants', '${report['totalFirstTime'] ?? 'N/A'}'),
            _field('Origins', report['participantOrigins'] ?? ''),
          ]),
          pw.SizedBox(height: 16),
          _section('Activity Description', [
            _field('What Was Done', report['activityDescription'] ?? ''),
            _field('Main Goal', report['mainGoal'] ?? ''),
            _field('Topics Covered', report['topicsCovered'] ?? ''),
          ]),
          pw.SizedBox(height: 16),
          _section('Results & Impact', [
            _field('What Went Well', report['whatWentWell'] ?? ''),
            _field('Challenges', report['whatDidNotGoWell'] ?? ''),
            _field('Participant Story', report['participantStory'] ?? ''),
          ]),
          pw.SizedBox(height: 16),
          _section('Budget', [
            _field('Total Cost', 'R ${(report['totalCost'] ?? 0).toStringAsFixed(2)}'),
            _field('Cost Per Person', 'R ${(report['costPerPerson'] ?? 0).toStringAsFixed(2)}'),
            _field('Funding Source', report['fundingSource'] ?? ''),
          ]),
          pw.SizedBox(height: 24),
          _signatureBlock(report),
        ],
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> generateMonthlyReportPdf(Map<String, dynamic> data) async {
    final pdf = pw.Document();
    final dateFmt = DateFormat('MMMM yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => [
          _header('MONTHLY REPORT — ${dateFmt.format(DateTime.now())}'),
          pw.SizedBox(height: 16),
          _section('Executive Summary', [
            _field('Total Activities', '${data['totalActivities'] ?? 0}'),
            _field('Total Participants', '${data['totalParticipants'] ?? 0}'),
            _field('Men / Women', '${data['totalMen'] ?? 0} / ${data['totalWomen'] ?? 0}'),
            _field('Total Budget Spent', 'R ${(data['totalCost'] ?? 0).toStringAsFixed(2)}'),
          ]),
          pw.SizedBox(height: 16),
          if (data['programmeBreakdown'] != null)
            _section('Programme Breakdown', _formatBreakdown(data['programmeBreakdown'])),
          pw.SizedBox(height: 16),
          _section('Generated', [
            pw.Paragraph(text: 'Generated by SALSO Workforce App', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
            pw.Paragraph(text: 'Date: ${dateFmt.format(DateTime.now())}', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
          ]),
        ],
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> generateSopRequestPdf(Map<String, dynamic> request) async {
    final pdf = pw.Document();
    final dateFmt = DateFormat('dd MMMM yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => [
          _header('${request['sopType']?.toString().replaceAll('_', ' ').toUpperCase()} REQUEST'),
          pw.SizedBox(height: 16),
          _section('Request Details', [
            _field('Title', request['title'] ?? ''),
            _field('Category', request['sopCategory'] ?? ''),
            _field('Submitted By', request['userDisplayName'] ?? ''),
            _field('Status', request['status'] ?? ''),
          ]),
          pw.SizedBox(height: 8),
          if (request['data'] != null) ...[
            _section('Form Data', _formatDataMap(request['data'])),
          ],
          pw.SizedBox(height: 16),
          pw.Paragraph(text: 'Filer Signature:', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
          if (request['filerSignature'] != null)
            pw.Image(pw.MemoryImage(Uri.parse(request['filerSignature']).data!.contentAsBytes()), height: 50),
          pw.SizedBox(height: 8),
          if (request['approvals'] != null)
            _section('Approvals', _formatApprovals(request['approvals'])),
          pw.SizedBox(height: 16),
          pw.Paragraph(text: 'Generated by SALSO Workforce App', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _header(String title) {
    return pw.Column(
      children: [
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 12),
          decoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.red, width: 2))),
          child: pw.Text(title, style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.red)),
        ),
      ],
    );
  }

  pw.Widget _section(String title, List<pw.Widget> children) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 8),
          decoration: pw.BoxDecoration(color: PdfColors.grey200),
          child: pw.Text(title, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        ),
        pw.SizedBox(height: 8),
        ...children,
        pw.SizedBox(height: 8),
      ],
    );
  }

  pw.Widget _field(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(width: 160, child: pw.Text(label, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700))),
          pw.Expanded(child: pw.Text(value, style: const pw.TextStyle(fontSize: 11))),
        ],
      ),
    );
  }

  pw.Widget _signatureBlock(Map<String, dynamic> report) {
    final columns = <pw.Widget>[];
    if (report['filerSignatureUrl'] != null) {
      columns.add(pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Filer Signature', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text(report['filerSignatureName'] ?? '', style: const pw.TextStyle(fontSize: 10)),
          pw.SizedBox(height: 4),
        ],
      ));
    }
    if (report['signOffSignatureUrl'] != null) {
      columns.add(pw.SizedBox(height: 12));
      columns.add(pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Manager Sign-Off', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text(report['signOffComment'] ?? '', style: const pw.TextStyle(fontSize: 10)),
        ],
      ));
    }
    return pw.Column(children: columns);
  }

  List<pw.Widget> _formatDataMap(Map<String, dynamic> data) {
    return data.entries.map((e) => _field(
      e.key.toString().replaceAll(RegExp(r'([a-z])([A-Z])'), r'$1 $2').replaceAll('_', ' '),
      e.value?.toString() ?? '',
    )).toList();
  }

  List<pw.Widget> _formatBreakdown(dynamic breakdown) {
    if (breakdown is! Map) return [];
    return breakdown.entries.map((e) => _field(e.key.toString(), (e.value ?? '').toString())).toList();
  }

  List<pw.Widget> _formatApprovals(Map<String, dynamic> approvals) {
    final widgets = <pw.Widget>[];
    approvals.forEach((step, value) {
      if (value is Map) {
        widgets.add(_field('Step: $step', value['approved'] == true ? 'Approved by ${value['byName'] ?? value['by']}' : 'Pending'));
        if (value['comment'] != null) {
          widgets.add(_field('  Comment', value['comment']));
        }
      }
    });
    return widgets;
  }
}
